version: "3"

services:
  postgres:
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: "thegame"
    ports:
      - '5432:5432'

  server:
    build: .
    command: node src/bin/server.js
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  migrate:
    build: .
    entrypoint: node_modules/.bin/sequelize db:migrate --config src/config/database/postgres.js --migrations-path src/database/migrations/
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  seed:
    build: .
    entrypoint: node_modules/.bin/sequelize db:seed:all --config src/config/database/postgres.js --seeders-path src/database/seeders/
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - migrate

  redis:
    image: redis:latest
    container_name: cache
    expose:
      - 6379

  # worker:
  #     build: .
  #     command: node worker.js
  #     ports:
  #       - "3001:3001"
  #     volumes:
  #       - .:/app
  #       - /app/node_modules
  #     depends_on:
  #       - postgres
  #     links:
  #       - postgres